### ISSUE TITLE
if Srho == Vrho error on finishing a run

### ISSUE THREAD

**Issue by Armatron44** [reflectometry/refl1d#122]
Hi,

I'm running to an error when refl1d completes a dream fit with the following:

> Traceback (most recent call last):
>   File "c:\users\sandy\anaconda3\envs\refl1d\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\users\sandy\anaconda3\envs\refl1d\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\sandy\anaconda3\envs\refl1d\Scripts\refl1d.exe\__main__.py", line 7, in <module>
>   File "c:\users\sandy\anaconda3\envs\refl1d\lib\site-packages\refl1d\main.py", line 45, in cli
>     bumps.cli.main()
>   File "c:\users\sandy\anaconda3\envs\refl1d\lib\site-packages\bumps\cli.py", line 707, in main
>     save_best(fitdriver, problem, best, view=opts.view)
>   File "c:\users\sandy\anaconda3\envs\refl1d\lib\site-packages\bumps\cli.py", line 132, in save_best
>     fitdriver.save(problem.output_path)
>   File "c:\users\sandy\anaconda3\envs\refl1d\lib\site-packages\bumps\fitters.py", line 1144, in save
>     self.problem.save(output_path)
>   File "c:\users\sandy\anaconda3\envs\refl1d\lib\site-packages\bumps\fitproblem.py", line 719, in save
>     f.save(basename + "-%d" % (i + 1))
>   File "c:\users\sandy\anaconda3\envs\refl1d\lib\site-packages\bumps\fitproblem.py", line 542, in save
>     self.fitness.save(basename)
>   File "c:\users\sandy\anaconda3\envs\refl1d\lib\site-packages\refl1d\experiment.py", line 221, in save
>     self.save_refl(basename)
>   File "c:\users\sandy\anaconda3\envs\refl1d\lib\site-packages\refl1d\experiment.py", line 301, in save_refl
>     self.probe.save(filename=basename+"-refl.dat", theory=theory,
>   File "c:\users\sandy\anaconda3\envs\refl1d\lib\site-packages\refl1d\probe.py", line 686, in save
>     fresnel_calculator = self.fresnel(substrate, surface)
>   File "c:\users\sandy\anaconda3\envs\refl1d\lib\site-packages\refl1d\probe.py", line 674, in fresnel
>     if Srho == Vrho:
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

I'm running python 3.8.8 with refl1d 0.8.14, bumps 0.8.0, numpy 1.20.1 & scipy 1.6.2. I don't run into this issue when using a different computer with a similar environment build  on the same fit problem (all packages that refl1d recommends are same versions). Any help on getting round this issue would be appreciated.

Thanks,

Sandy

**Comment by bmaranville** [comment]
Hello - if you are using the "Material" class in your model, there is a possibility that the most recent version of periodictable (==1.6.0) is causing an issue.   A workaround is to install periodictable==1.5.3
Can you tell me if that works?

**Comment by Armatron44** [comment]
Hi Brian,

Thanks for the suggestion. My periodictable was == 1.6.0, so I downgraded as suggested and retried. 
It now works without errors, thanks!
