### ISSUE TITLE
Export Results / Save hangs upon errors in serialization

### ISSUE THREAD

**Issue by purnimab** [reflectometry/refl1d#174]
When exporting results, an error in saving out the .json model file (in this case, because I had parameterized using functions, for which serialization has not yet been implemented) prevents the exporting of any subsequent files, such as mcmc or plot files. A simple try catch along with a warning to the user about which files were not properly saved should be a sufficient fix.

`Traceback (most recent call last):
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\refl1d\experiment.py", line 228, in save_json
    experiment = to_dict(self)
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 192, in to_dict
    return Serializer(use_refs=use_refs).to_dict(obj)
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 164, in to_dict
    output = self.dataclass_to_dict(obj, include=include, exclude=exclude)
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 152, in dataclass_to_dict
    output = dict([(f.name, self.to_dict(getattr(dclass, f.name))) for f in all_fields])
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 152, in <listcomp>
    output = dict([(f.name, self.to_dict(getattr(dclass, f.name))) for f in all_fields])
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 171, in to_dict
    return type(obj)(self.to_dict(v) for v in obj)
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 171, in <genexpr>
    return type(obj)(self.to_dict(v) for v in obj)
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 164, in to_dict
    output = self.dataclass_to_dict(obj, include=include, exclude=exclude)
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 152, in dataclass_to_dict
    output = dict([(f.name, self.to_dict(getattr(dclass, f.name))) for f in all_fields])
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 152, in <listcomp>
    output = dict([(f.name, self.to_dict(getattr(dclass, f.name))) for f in all_fields])
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 171, in to_dict
    return type(obj)(self.to_dict(v) for v in obj)
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 171, in <genexpr>
    return type(obj)(self.to_dict(v) for v in obj)
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 164, in to_dict
    output = self.dataclass_to_dict(obj, include=include, exclude=exclude)
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 152, in dataclass_to_dict
    output = dict([(f.name, self.to_dict(getattr(dclass, f.name))) for f in all_fields])
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 152, in <listcomp>
    output = dict([(f.name, self.to_dict(getattr(dclass, f.name))) for f in all_fields])
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 164, in to_dict
    output = self.dataclass_to_dict(obj, include=include, exclude=exclude)
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 152, in dataclass_to_dict
    output = dict([(f.name, self.to_dict(getattr(dclass, f.name))) for f in all_fields])
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 152, in <listcomp>
    output = dict([(f.name, self.to_dict(getattr(dclass, f.name))) for f in all_fields])
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 164, in to_dict
    output = self.dataclass_to_dict(obj, include=include, exclude=exclude)
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 152, in dataclass_to_dict
    output = dict([(f.name, self.to_dict(getattr(dclass, f.name))) for f in all_fields])
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 152, in <listcomp>
    output = dict([(f.name, self.to_dict(getattr(dclass, f.name))) for f in all_fields])
  File "C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\bumps\serialize.py", line 188, in to_dict
    raise ValueError("obj %s is not serializable" % str(obj))
ValueError: obj <bumps.parameter.UserFunction object at 0x000001C21A939060> is not serializable
C:\Users\ppb1\Documents\Refl1d-0.8.15-Webview-Jupyter\env\lib\site-packages\refl1d\experiment.py:235: UserWarning:

failed to create json structure for model`

**Comment by bmaranville** [comment]
Not sure if this is specific to webview - if not, will apply fix to master branch too.

**Comment by bmaranville** [comment]
Huh... There is already a try/catch (and a helpful warning!) in that save_json function.  I wonder why it's not working as expected?  I'll try making a simple model with a Function to see if I can reproduce.

**Comment by purnimab** [comment]
Version used:
[Refl1D-windows-exe-webview-jupyter.tar.gz](https://github.com/reflectometry/refl1d/releases/download/sid/Refl1D-windows-exe-webview-jupyter.tar.gz)
201 MB
Dec 5, 2023

**Comment by bmaranville** [comment]
Ah yes - I see there's no try/catch around the serialization of the fitProblem in `bumps.webview.server.api.export_results`.  I just added one:  see https://github.com/bumps/bumps/commit/e942a12c04891b39d8a8e67c6c173195e3544e2b
